### ISSUE TITLE
How to install project?

### ISSUE THREAD

**Issue by ciases** [outpunk/postcss-modules-example#2]
Hi!
I've clone this repo, run `npm install` and get an error:

``` bash
$ gulp
module.js:341
    throw err;
    ^
Error: Cannot find module './gulpfile.babel.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/ciases/Projects/ciases/postcss-modules-example/Gulpfile.js:2:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

I guess problem with `babel`.
Please add some install information to `README.md`.

**Comment by sandiprb** [comment]
@ciases
It's because of file name capitalisation.  
This should fix it : https://github.com/outpunk/postcss-modules-example/pull/5
